dist: bionic
language: cpp

before_install:
  - sudo apt-get install -y openjdk-11-jdk
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt-get install -y curl
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get -q update
  - sudo apt-get install -y bazel

script:
  - bazel test //...
